/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as CategorySlugIndexRouteImport } from './routes/category.$slug.index'
import { Route as CategorySlugItemIdRouteImport } from './routes/category.$slug.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugIndexRoute = CategorySlugIndexRouteImport.update({
  id: '/category/$slug/',
  path: '/category/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugItemIdRoute = CategorySlugItemIdRouteImport.update({
  id: '/category/$slug/$itemId',
  path: '/category/$slug/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/category/$slug/$itemId': typeof CategorySlugItemIdRoute
  '/category/$slug/': typeof CategorySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/category/$slug/$itemId': typeof CategorySlugItemIdRoute
  '/category/$slug': typeof CategorySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favourites': typeof FavouritesRoute
  '/category/$slug/$itemId': typeof CategorySlugItemIdRoute
  '/category/$slug/': typeof CategorySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/favourites' | '/category/$slug/$itemId' | '/category/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favourites' | '/category/$slug/$itemId' | '/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/favourites'
    | '/category/$slug/$itemId'
    | '/category/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavouritesRoute: typeof FavouritesRoute
  CategorySlugItemIdRoute: typeof CategorySlugItemIdRoute
  CategorySlugIndexRoute: typeof CategorySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/': {
      id: '/category/$slug/'
      path: '/category/$slug'
      fullPath: '/category/$slug/'
      preLoaderRoute: typeof CategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/$itemId': {
      id: '/category/$slug/$itemId'
      path: '/category/$slug/$itemId'
      fullPath: '/category/$slug/$itemId'
      preLoaderRoute: typeof CategorySlugItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavouritesRoute: FavouritesRoute,
  CategorySlugItemIdRoute: CategorySlugItemIdRoute,
  CategorySlugIndexRoute: CategorySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
